---
- name: Instalação do GitLab CE
  hosts: all
  become: yes

  tasks:
    - name: Atualizar o Cache de Pacotes
      apt:
        update_cache: yes

    - name: Download scripts de instalação GitLab
      get_url:
        url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
        dest: "/tmp/script.deb.sh"

    - name: Adicionando Repositórios do GitLab
      command: "bash /tmp/script.deb.sh"
      become: yes

    - name: Instalação do GitLab CE
      apt:
        name: gitlab-ce
        state: present
        
    - name: Executar gitlab-ctl reconfigure
      command: "gitlab-ctl reconfigure"
      become: yes
